services:
  tusd:
    image: tusproject/tusd:v2.8.0
    container_name: tusd
    ports:
      - "1337:8080"
    volumes:
      - ./tusd-data:/srv/tusd-data
    networks:
      - tusd

networks:
  tusd:
    driver: bridge
